### ISSUE TITLE
Recursive field in decodable struct

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang-nursery/rustc-serialize#131]
I want to deserialize json to struct which has a field with any json instance:

```rust
#[derive(RustcDecodable, RustcEncodable)]
pub struct TestStruct  {
    data_int: u8,
    data_str: String,
    data_map: BTreeMap<String, Json>,
}
```

But compiler fails with:
```rust
src\worker.rs:16:10: 16:24 error: the trait `rustc_serialize::serialize::Decodable` is not implemented for the type `rustc_serialize::json::Json` [E0277]
```

If I use definite type like `String` instead of `Json` program compiles well.
Why is it impossible to decode to a resursive struct? I see the Decodable not implemented, but maybe there is meaning to make a PR to fix it? I can to spend some time to do it.

**Comment by alexcrichton** [comment]
There error here is actually quite illuminating! The `Decodable` trait is indeed not defined for `Json`, and `Decodable` is only implemented for `BTreeMap` if the value also implements `Decodable`. This implementation unfortunately can't exist due to the design of this library, but using a concrete struct should work!

**Comment by DenisKolodin** [comment]
Thank you for explanation! This is a useful feature for the next reimplementation of this lib.
