### ISSUE TITLE
SocketAddr/IpAddr

### ISSUE THREAD

**Issue by ustulation** [rust-lang-nursery/rustc-serialize#179]
Hey, would you guys be interested in a PR that allows `std::net::SocketAddr/IpAddr` to be (de)serialised ? I need to send address to peers frequently and end up converting them to string and (de)serialising that. Was wondering if that could be added to this crate instead so that it wont be needed to be handcoded any longer.

**Comment by dtolnay** [comment]
Are you able to use Serde instead? Serde supports SocketAddr and IpAddr already.

**Comment by ustulation** [comment]
Aha i've never tried it actually. Let me try serde then - thanks. Is this going to be abandoned/deprecated soon then ?

**Comment by dtolnay** [comment]
Not necessarily abandoned/deprecated but rustc-serialize has not been actively developed for the past year and a half - compare [graph](https://github.com/rust-lang-nursery/rustc-serialize/graphs/contributors) vs [graph](https://github.com/serde-rs/serde/graphs/contributors) - and major players (toml, bincode) have dropped rustc-serialize support now that Serde's derives are stable.

**Comment by alexcrichton** [comment]
Yeah FWIW I'd highly recommend using serde instead of rustc-serialize nowadays. I hope to bring up with the libs team soon an "official deprecation" of this crate where we can close out all the issues and such that @dtolnay has been so willing to keep up to date with "don't forget serde can do this" :)
