### ISSUE TITLE
Confused between serialize and rustc-serialize

### ISSUE THREAD

**Issue by winding-lines** [rust-lang-nursery/rustc-serialize#38]
What is the relationship between serialize::json and rustc-serialize::json?

The doc pages look very similar to me... 
http://doc.rust-lang.org/serialize/json/
http://doc.rust-lang.org/rustc-serialize/rustc-serialize/json/index.html

**Comment by BurntSushi** [comment]
`rustc-serialize` used to be included in the standard Rust distribution with the name `serialize`. It has since moved to its own package on `crates.io`. I think I can say that you should always be using `rustc-serialize`.

The reason why this move occurred, AFAIK, is that the serialization infrastructure probably isn't going to be stabilized before Rust 1.0. But, it's *extremely* useful. The Rust 1.0 stable channel will disallow all uses of unstable things, so the only way to permit continued use of `rustc-serialize` is to split it out of Rust proper and into its own separate package.

**Comment by winding-lines** [comment]
Thanks for the explanation :) Should we then remove the docs from http://doc.rust-lang.org/serialize/json/ ?

**Comment by Byron** [comment]
+1 to downing these docs !

I just lost 30 minutes to figure out how to deserialize json ! Reason was that I of course found the 'serialize' documentation first, which caused all sorts of problems as both crates got mixed up in my code.

It really adds to my frustration as everything I attempt quickly ends up being much more difficult than anticipated. Sure, it's alpha, but there is no need to unnecessarily confuse anyone :).

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
